In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [5]:
def load_data(file_path):
    return pd.read_csv(file_path, delimiter=';')

df_math = load_data("student-mat.csv")
df_por = load_data("student-por.csv")

drop_columns = ['studytime', 'famsize', 'Pstatus', 'Medu', 'Fedu', 'schoolsup', 'famsup', 'paid', 'famrel', 'goout', 'Dalc', 'Walc', 'G1', 'G2', 'G3']
df_math = df_math.drop(columns=drop_columns)
df_por = df_por.drop(columns=drop_columns)

In [6]:
def cap_outliers(df, column, cap_value):
    df[column] = df[column].apply(lambda x: min(x, cap_value))
    return df

df_math = cap_outliers(df_math, 'absences', 30)
df_por = cap_outliers(df_por, 'absences', 30)

In [7]:
def display_cleaned_data(df, num_rows=10):
    from IPython.display import display
    display(df.head(num_rows))

display_cleaned_data(df_math)
display_cleaned_data(df_por)

,school,sex,age,address,Mjob,Fjob,reason,guardian,traveltime,failures,activities,nursery,higher,internet,romantic,freetime,health,absences
0,GP,F,18,U,at_home,teacher,course,mother,2,0,no,yes,yes,no,no,3,3,6
1,GP,F,17,U,at_home,other,course,father,1,0,no,no,yes,yes,no,3,3,4
2,GP,F,15,U,at_home,other,other,mother,1,3,no,yes,yes,yes,no,3,3,10
3,GP,F,15,U,health,services,home,mother,1,0,yes,yes,yes,yes,yes,2,5,2
4,GP,F,16,U,other,other,home,father,1,0,no,yes,yes,no,no,3,5,4
5,GP,M,16,U,services,other,reputation,mother,1,0,yes,yes,yes,yes,no,4,5,10
6,GP,M,16,U,other,other,home,mother,1,0,no,yes,yes,yes,no,4,3,0
7,GP,F,17,U,other,teacher,home,mother,2,0,no,yes,yes,no,no,1,1,6
8,GP,M,15,U,services,other,home,mother,1,0,no,yes,yes,yes,no,2,1,0
9,GP,M,15,U,other,other,home,mother,1,0,yes,yes,yes,yes,no,5,5,0

,school,sex,age,address,Mjob,Fjob,reason,guardian,traveltime,failures,activities,nursery,higher,internet,romantic,freetime,health,absences
0,GP,F,18,U,at_home,teacher,course,mother,2,0,no,yes,yes,no,no,3,3,4
1,GP,F,17,U,at_home,other,course,father,1,0,no,no,yes,yes,no,3,3,2
2,GP,F,15,U,at_home,other,other,mother,1,0,no,yes,yes,yes,no,3,3,6
3,GP,F,15,U,health,services,home,mother,1,0,yes,yes,yes,yes,yes,2,5,0
4,GP,F,16,U,other,other,home,father,1,0,no,yes,yes,no,no,3,5,0
5,GP,M,16,U,services,other,reputation,mother,1,0,yes,yes,yes,yes,no,4,5,6
6,GP,M,16,U,other,other,home,mother,1,0,no,yes,yes,yes,no,4,3,0
7,GP,F,17,U,other,teacher,home,mother,2,0,no,yes,yes,no,no,1,1,2
8,GP,M,15,U,services,other,home,mother,1,0,no,yes,yes,yes,no,2,1,0
9,GP,M,15,U,other,other,home,mother,1,0,yes,yes,yes,yes,no,5,5,0